# ── Overview ───────────────────────────────────────────────────────────────────
#
# A sliding-tile puzzle game built with Python's tkinter GUI toolkit.
#
# How it works:
#   1. A random abstract image (the "scene") is generated by drawing coloured
#      geometric shapes onto a blank canvas.
#   2. The scene is sliced into an N×N grid of rectangular tiles.
#   3. The tiles are shuffled into a random order.
#   4. The player drags tiles to restore the original image.
#
# Bonding:
#   Two neighbouring tiles are "bonded" when they are both in the correct
#   positions relative to each other (i.e. their original row/column numbers
#   differ by exactly 1 in the direction they are touching).  Bonded tiles
#   move together as a group when dragged, which lets the player shift
#   correctly assembled sections of the puzzle in one move.
#
# Tile data:
#   self.tiles is an N×N list-of-lists.  Each cell holds a small dictionary:
#       {'or': original_row, 'oc': original_col}
#   'or' and 'oc' record where this tile came from in the solved image.
#   When the puzzle is solved every tile satisfies  tiles[r][c]['or']==r
#   and  tiles[r][c]['oc']==c.
#
# ── Imports ────────────────────────────────────────────────────────────────────

import tkinter as tk                    # Python's built-in GUI framework
from PIL import Image, ImageDraw, ImageTk  # Pillow: image creation and manipulation
import random
import math

# ── Constants ──────────────────────────────────────────────────────────────────

SZ       = 500                        # Width  of the generated scene image (pixels)
SZ_H     = round(SZ * 5 / 3)         # Height of the generated scene image.
                                      # Tiles have a 3-wide : 5-tall aspect ratio,
                                      # matching the proportions of commercial tile sets.
MARGIN   = 30                         # Gap (pixels) between the canvas edge and the grid
BW       = 2                          # Half-width of the border lines drawn between tiles
CANVAS_W = 520                        # Width  of the tkinter canvas widget (pixels)
CANVAS_H = round(2*MARGIN + (CANVAS_W - 2*MARGIN) * 5 / 3)   # Height of the canvas (≈ 827)

# Colour of the canvas background (the border area outside the tile grid).
# This blue-grey shade is chosen to contrast with the vivid tile colours.
OUT_R, OUT_G, OUT_B = 148, 168, 225
OUT_HUE  = 220    # The hue (degrees on the colour wheel) of the background colour
HUE_AVOID = 40    # Tile colours whose hue falls within this many degrees of the
                  # background hue are shifted away to keep tiles visually distinct.

# ── Color helpers ──────────────────────────────────────────────────────────────
#
# Colours are generated in HSL (Hue, Saturation, Lightness) space because it is
# easy to produce vivid, varied colours there, then converted to RGB (Red, Green,
# Blue) for drawing.
#
# Hue       : position on the colour wheel, 0-360 degrees (0=red, 120=green, 240=blue)
# Saturation: how vivid the colour is, 0=grey, 1=fully saturated
# Lightness : how light/dark, 0=black, 0.5=pure colour, 1=white

def hsl_to_rgb(h, s, l):
    """Convert an HSL colour to an (R, G, B) tuple with values 0-255."""
    h = h % 360
    a = s * min(l, 1.0 - l)   # chroma-related factor
    def f(n):
        # Standard HSL-to-RGB formula; n selects which colour channel (R/G/B)
        k = (n + h / 30.0) % 12
        return l - a * max(-1.0, min(k - 3.0, 9.0 - k, 1.0))
    return int(f(0)*255), int(f(8)*255), int(f(4)*255)

# _hue is a one-element list so that rand_color() can update it across calls
# (a plain variable could not be modified inside a nested function in older Python).
_hue = [random.random() * 360]

def rand_color():
    """
    Return a random vivid (R, G, B) colour for drawing shapes.

    Uses the "golden-angle" increment (137.5°) to step around the colour wheel,
    which spreads colours evenly and avoids repeats.  A small random jitter is
    added so successive colours are not perfectly uniform.  Hues too close to the
    background colour are nudged away so shapes always stand out.
    """
    _hue[0] = (_hue[0] + 137.5) % 360        # advance by the golden angle
    h = (_hue[0] + random.uniform(-10, 10) + 360) % 360   # add jitter
    # If the hue is too close to the background colour, push it away
    if abs(((h - OUT_HUE + 540) % 360) - 180) < HUE_AVOID:
        h = (OUT_HUE + HUE_AVOID + 10 + random.random() * 20) % 360
    r, g, b = hsl_to_rgb(h, 0.75 + random.random()*0.25, 0.45 + random.random()*0.20)
    return r, g, b

def rand_bg():
    """
    Return a random muted (R, G, B) colour for the scene background.

    Low saturation (0.08-0.28) and variable lightness produce a wide range of
    subtle washes — dark charcoal, dusty pastels, pale stone — that let the
    brighter foreground shapes stand out.
    """
    return hsl_to_rgb(random.random()*360,
                      0.08 + random.random()*0.20,
                      0.10 + random.random()*0.55)

def rnd(a, b): return a + (b - a) * random.random()   # random float in [a, b)
def ri(a, b):  return random.randint(a, b)             # random int   in [a, b]

# ── Geometry helpers ───────────────────────────────────────────────────────────
#
# These functions return lists of (x, y) vertex coordinates that describe shapes.
# They are passed to Pillow's drw.polygon() to fill the shape with colour.

def poly_pts(cx, cy, r, sides, rot=0.0):
    """
    Return the vertices of a regular polygon.

    cx, cy  : centre of the polygon
    r       : radius (distance from centre to each vertex)
    sides   : number of sides (3=triangle, 4=square, 6=hexagon, …)
    rot     : rotation angle in radians (0 = first vertex pointing straight up)
    """
    return [(cx + r*math.cos((i/sides)*2*math.pi - math.pi/2 + rot),
             cy + r*math.sin((i/sides)*2*math.pi - math.pi/2 + rot))
            for i in range(sides)]

def star_pts(cx, cy, r1, r2, n, rot=0.0):
    """
    Return the vertices of an n-pointed star.

    cx, cy  : centre
    r1      : outer radius (tips of the star)
    r2      : inner radius (indentations between tips)
    n       : number of points
    rot     : rotation in radians
    """
    pts = []
    for i in range(n * 2):        # alternate between outer and inner vertices
        a  = (i/n)*math.pi - math.pi/2 + rot
        rr = r1 if i % 2 == 0 else r2
        pts.append((cx + rr*math.cos(a), cy + rr*math.sin(a)))
    return pts

def rot_rect(cx, cy, w, h, rot):
    """
    Return the four corners of a rotated rectangle.

    cx, cy : centre
    w, h   : width and height before rotation
    rot    : rotation angle in radians
    """
    hw, hh = w/2, h/2
    cs, sn = math.cos(rot), math.sin(rot)
    # Rotate each of the four corners around the centre
    return [(cx + x*cs - y*sn, cy + x*sn + y*cs)
            for x, y in [(-hw,-hh),(hw,-hh),(hw,hh),(-hw,hh)]]

def ellipse_pts(cx, cy, a, b, rot, n=32):
    """
    Return n points approximating a rotated ellipse as a polygon.

    cx, cy : centre
    a      : semi-major axis (half-width before rotation)
    b      : semi-minor axis (half-height before rotation)
    rot    : rotation in radians
    n      : number of polygon vertices used to approximate the ellipse
    """
    cs, sn = math.cos(rot), math.sin(rot)
    return [(cx + a*math.cos(t)*cs - b*math.sin(t)*sn,
             cy + a*math.cos(t)*sn + b*math.sin(t)*cs)
            for t in (i/n*2*math.pi for i in range(n))]

# ── Scene generation ───────────────────────────────────────────────────────────
#
# The scene is built up in six layers, each handled by its own function:
#
#   _draw_large_shapes   – 2-3 big shapes that may bleed off the image edges
#   _draw_medium_shapes  – 4-6 mid-sized shapes fully or mostly on-canvas
#   _draw_accent_shapes  – 3-5 small shapes placed wholly within the image
#   _draw_bursts         – 1-3 radial ray/burst patterns
#   _draw_lines          – 1-3 thick diagonal lines
#   _draw_vignette       – darkened-edge overlay for depth
#
# All layer functions take the Pillow ImageDraw object (drw), the image
# dimensions (W, H), and any extra data they need (e.g. bg_rgb for the
# donut punch-through colour and vignette brightness calculation).

def _draw_shape(drw, pts_or_bbox, col, alpha=215):
    """
    Draw one shape onto the image via the Pillow drawing context drw.

    pts_or_bbox : either a list of (x,y) vertex tuples (→ polygon)
                  or a flat [x0,y0,x1,y1] bounding box  (→ ellipse)
    col         : (R, G, B) fill colour
    alpha       : opacity, 0=transparent, 255=solid; default 215 gives slight
                  translucency so underlying shapes show through faintly
    """
    rgba = col + (alpha,)
    if isinstance(pts_or_bbox[0], tuple):
        drw.polygon(pts_or_bbox, fill=rgba)
    else:
        drw.ellipse(pts_or_bbox, fill=rgba)


def _draw_large_shapes(drw, W, H):
    """
    Layer 1: draw 2-3 large shapes that may extend beyond the image edges.

    These big shapes establish the overall colour mood of the scene.  Centres
    are allowed to sit up to 12% outside the canvas, so shapes can bleed off
    any edge, giving the impression of an even larger composition.

    Shape types chosen at random: circle/oval, rotated rectangle, triangle,
    tilted ellipse, hexagon, or rotated square.
    """
    for _ in range(ri(2, 3)):
        cx, cy = rnd(-W*.12, W*1.12), rnd(-H*.12, H*1.12)  # centre may be off-canvas
        rot = rnd(0, 2*math.pi)
        col = rand_color()
        sz  = rnd(W*.17, W*.33)    # 17-33% of image width
        t   = ri(0, 5)             # pick a random shape type
        if   t == 0: _draw_shape(drw, [cx-sz, cy-sz, cx+sz, cy+sz], col)                  # circle
        elif t == 1: _draw_shape(drw, rot_rect(cx, cy, sz*2, sz*rnd(.7,1.1), rot), col)   # rotated rect
        elif t == 2: _draw_shape(drw, poly_pts(cx, cy, sz, 3, rot), col)                   # triangle
        elif t == 3: _draw_shape(drw, ellipse_pts(cx, cy, sz, sz*rnd(.38,.65), rot), col) # ellipse
        elif t == 4: _draw_shape(drw, poly_pts(cx, cy, sz, 6, rot), col)                   # hexagon
        else:        _draw_shape(drw, poly_pts(cx, cy, sz, 4, rot), col)                   # rotated square


def _draw_medium_shapes(drw, W, H, bg_rgb):
    """
    Layer 2: draw 4-6 medium shapes.

    Centres are kept within 8% of the canvas edges.  One special shape type
    is a donut (annulus): a circle with a smaller circle punched through its
    centre using the background colour.  All other types are solid polygons or
    a plain circle.

    bg_rgb is needed so the donut's hole can be painted in the background colour.
    """
    br, bg_c, bb = bg_rgb   # unpack so we can use bg colour for the donut hole
    for _ in range(ri(4, 6)):
        cx, cy = rnd(-W*.08, W*1.08), rnd(-H*.08, H*1.08)
        rot = rnd(0, 2*math.pi)
        col = rand_color()
        sz  = rnd(W*.07, W*.16)    # 7-16% of image width
        t   = ri(0, 7)
        if   t == 0: _draw_shape(drw, poly_pts(cx, cy, sz, 4, rot), col)                         # square
        elif t == 1: _draw_shape(drw, poly_pts(cx, cy, sz, 5, rot), col)                         # pentagon
        elif t == 2: _draw_shape(drw, poly_pts(cx, cy, sz, 6, rot), col)                         # hexagon
        elif t == 3: _draw_shape(drw, [cx-sz, cy-sz, cx+sz, cy+sz], col)                         # circle
        elif t == 4:
            # Donut / annulus: draw a solid circle, then paint the background
            # colour over a smaller concentric circle to create the hole
            _draw_shape(drw, [cx-sz, cy-sz, cx+sz, cy+sz], col)
            inn = sz * .52
            drw.ellipse([cx-inn, cy-inn, cx+inn, cy+inn], fill=(br, bg_c, bb))
        elif t == 5: _draw_shape(drw, poly_pts(cx, cy, sz, 4, rot + math.pi/4), col)             # diamond
        else:        _draw_shape(drw, rot_rect(cx, cy, sz*rnd(1.2,2.2), sz*rnd(.5,.9), rot), col) # wide rect


def _draw_accent_shapes(drw, W, H):
    """
    Layer 3: draw 3-5 small accent shapes placed fully within the image bounds.

    These tiny details add visual interest at a fine scale.  Slightly higher
    opacity (alpha=230) makes them a little more solid than the larger layers.
    Shape types: 5-pointed star, triangle, or circle.
    """
    for _ in range(ri(3, 5)):
        cx, cy = rnd(0, W), rnd(0, H)
        rot = rnd(0, 2*math.pi)
        col = rand_color()
        sz  = rnd(W*.028, W*.072)   # 3-7% of image width
        t   = ri(0, 2)
        if   t == 0: _draw_shape(drw, star_pts(cx, cy, sz, sz*.42, 5, rot), col, 230)  # 5-pointed star
        elif t == 1: _draw_shape(drw, poly_pts(cx, cy, sz, 3, rot), col, 230)           # triangle
        else:        _draw_shape(drw, [cx-sz, cy-sz, cx+sz, cy+sz], col, 230)           # circle


def _draw_bursts(drw, W, H):
    """
    Layer 4: draw 1-3 radial burst / ray patterns.

    Each burst fans out evenly-spaced lines from a small inner circle to a
    larger outer radius, alternating between two colours.  This creates a
    starburst or sun-ray effect.

    inn : inner radius where rays begin (kept small to look like a hub)
    out : outer radius where rays end
    """
    for _ in range(ri(1, 3)):
        cx, cy  = rnd(W*.12, W*.88), rnd(H*.12, H*.88)  # centre well inside the image
        c1, c2  = rand_color(), rand_color()             # alternating ray colours
        n_rays  = ri(10, 18)
        inn     = W * rnd(.008, .020)   # inner radius (start of each ray)
        out     = W * rnd(.08,  .18)    # outer radius (end   of each ray)
        for i in range(n_rays):
            a   = (i / n_rays) * 2 * math.pi   # angle for this ray
            col = c1 if i % 2 == 0 else c2
            lw  = max(1, round(rnd(1.5, 4)))
            drw.line([(cx + inn*math.cos(a), cy + inn*math.sin(a)),
                      (cx + out*math.cos(a), cy + out*math.sin(a))],
                     fill=col, width=lw)


def _draw_lines(drw, W, H):
    """
    Layer 5: draw 1-3 thick diagonal lines across the scene.

    Endpoints are allowed up to 8% outside the canvas so lines can run
    fully edge-to-edge without starting or ending visibly on-canvas.
    """
    for _ in range(ri(1, 3)):
        drw.line([(rnd(-W*.08, W*1.08), rnd(-H*.08, H*1.08)),
                  (rnd(-W*.08, W*1.08), rnd(-H*.08, H*1.08))],
                 fill=rand_color(), width=max(1, round(rnd(4, 8))))


def _draw_vignette(img, W, H, bg_rgb):
    """
    Layer 6: apply a vignette (darkened-edge overlay) to the image in-place.

    A vignette makes the image look more polished and slightly three-dimensional
    by darkening the edges.  We build a greyscale "mask" image: pixels with a
    high mask value darken the image at that position; a mask value of 0
    leaves the image unchanged.

    The mask is built by drawing concentric ellipses with decreasing darkness
    from the outside in.  The outermost ring is darkest; the centre fades to
    fully transparent, leaving the middle of the image at full brightness.

    Darker backgrounds get a lighter vignette (max_a is smaller) so the effect
    is perceptible without making an already-dark scene look black around the edges.
    """
    br, bg_c, bb = bg_rgb
    lum   = (br + bg_c + bb) / (3 * 255)         # average brightness 0-1
    max_a = int((0.20 + 0.35*(1 - lum)) * 255)   # darker bg → lighter vignette
    mask  = Image.new('L', (W, H), max_a)         # start: every pixel at max darkness
    md    = ImageDraw.Draw(mask)
    for i in range(1, 36):
        t     = i / 35                                  # 0 → 1 as i increases
        alpha = int(max_a * max(0.0, 1 - t**0.55))     # fade to 0 at the centre
        # Scale x and y margins proportionally to the image dimensions so the
        # vignette ellipses maintain the same aspect ratio as the image.
        # Using min(W, H) for both would make the ellipses narrow and tall on a
        # portrait image, leaving the top/bottom unnaturally dark and creating a
        # visible oval artifact when the solved puzzle is viewed without borders.
        mx    = int(t * W * 0.48)                      # x-margin proportional to width
        my    = int(t * H * 0.48)                      # y-margin proportional to height
        md.ellipse([mx, my, W-mx, H-my], fill=alpha)   # draw progressively smaller ellipse
    # Paste a black layer using the mask: high mask value → more darkening, 0 → none
    img.paste(Image.new('RGB', (W, H), (0, 0, 0)), mask=mask)


def generate_scene(bg_rgb):
    """
    Create and return a randomly generated abstract image (a Pillow Image object).

    The image is SZ pixels wide and SZ_H pixels tall.  It is later sliced into
    tiles by the app.  A new random scene is generated for each new puzzle.

    bg_rgb : (R, G, B) tuple for the background colour
    """
    W, H = SZ, SZ_H
    br, bg_c, bb = bg_rgb
    img = Image.new('RGB', (W, H), (br, bg_c, bb))   # blank image filled with bg colour
    drw = ImageDraw.Draw(img, 'RGBA')                 # drawing context; RGBA allows alpha

    _draw_large_shapes(drw, W, H)
    _draw_medium_shapes(drw, W, H, bg_rgb)
    _draw_accent_shapes(drw, W, H)
    _draw_bursts(drw, W, H)
    _draw_lines(drw, W, H)
    _draw_vignette(img, W, H, bg_rgb)

    return img

# ── App ────────────────────────────────────────────────────────────────────────

class TilePuzzleApp(tk.Tk):
    """
    The main application window.  Inherits from tk.Tk so the instance IS the
    root window — no separate root object is needed.

    Key instance variables
    ──────────────────────
    self.N        : current grid size (4, 5, or 6), giving an N×N puzzle
    self.tiles    : N×N list-of-lists; each cell is {'or': row, 'oc': col}
                    recording the tile's original position in the solved image
    self.drag     : None when idle; a dictionary of drag state while the player
                    is holding a tile (see _on_down for the keys)
    self.solved   : True once the puzzle has been completed
    self.history  : list of previous tile grids, used by Undo
    self._photos  : dict mapping (orig_row, orig_col) → PhotoImage
                    Pillow images must be kept here or Python's garbage collector
                    will delete them and the canvas will show blank tiles
    """

    def __init__(self):
        super().__init__()
        self.title("Tile Puzzle")
        self.resizable(False, False)
        self.configure(bg='#e8eaf0')

        self.N       = 5       # default grid size
        self.tiles   = []
        self.drag    = None
        self.solved  = False
        self.history = []
        self._photos = {}

        self._build_ui()
        self.build_grid()

    # ── UI ────────────────────────────────────────────────────────────────────

    def _build_ui(self):
        """
        Create the control bar (status label, grid size selector, Undo and New
        buttons) and the canvas where the puzzle is drawn.
        """
        # ── Control bar ───────────────────────────────────────────────────────
        ctrl = tk.Frame(self, bg='#d4edda', padx=10, pady=8)
        ctrl.pack(fill='x')

        # Status label: shows messages like "Dragging tile" or "Puzzle solved!"
        self.status_var = tk.StringVar(value='Drag a tile or bonded group to move it.')
        tk.Label(ctrl, textvariable=self.status_var, font=('Helvetica', 11),
                 bg='#d4edda', fg='#155724').pack(side='left', expand=True, anchor='w')

        # Grid-size selector: choosing a new size immediately starts a new puzzle
        tk.Label(ctrl, text='Grid:', font=('Helvetica', 11),
                 bg='#d4edda', fg='#155724').pack(side='left', padx=(0, 4))
        self.grid_var = tk.StringVar(value='5')
        tk.OptionMenu(ctrl, self.grid_var, '4', '5', '6',
                      command=lambda _: self.build_grid()
                      ).pack(side='left', padx=(0, 6))

        # Undo button: starts disabled; enabled whenever there is history
        self.undo_btn = tk.Button(ctrl, text='↩ Undo', font=('Helvetica', 11),
                                   state='disabled', command=self.undo,
                                   relief='flat', padx=10)
        self.undo_btn.pack(side='left', padx=(0, 4))

        # New button: generates a brand-new shuffled puzzle
        tk.Button(ctrl, text='↺ New', font=('Helvetica', 11),
                  command=self.build_grid, relief='flat', padx=10).pack(side='left')

        # ── Canvas ────────────────────────────────────────────────────────────
        # The canvas background colour is the border area visible around (and
        # potentially between) tiles.
        bg_hex = '#{:02x}{:02x}{:02x}'.format(OUT_R, OUT_G, OUT_B)
        self.canvas = tk.Canvas(self, width=CANVAS_W, height=CANVAS_H,
                                 bg=bg_hex, highlightthickness=0, cursor='hand2')
        self.canvas.pack()

        # Bind mouse events for drag-and-drop interaction
        self.canvas.bind('<ButtonPress-1>',   self._on_down)   # mouse button pressed
        self.canvas.bind('<B1-Motion>',       self._on_move)   # mouse moved while pressed
        self.canvas.bind('<ButtonRelease-1>', self._on_up)     # mouse button released

    # ── Coordinate helpers ────────────────────────────────────────────────────
    #
    # The tile grid sits inside a MARGIN-pixel border on all sides of the canvas.
    # Tiles are placed at column c, row r starting from the top-left corner.
    #
    #   Canvas x = MARGIN + c * tile_width
    #   Canvas y = MARGIN + r * tile_height
    #
    # Tiles are taller than wide (5:3 ratio), so tile_height > tile_width.

    def _tw(self): return (CANVAS_W - 2*MARGIN) / self.N   # tile width  in pixels
    def _th(self): return (CANVAS_H - 2*MARGIN) / self.N   # tile height in pixels (≈ _tw × 5/3)
    def _tx(self, c): return MARGIN + c * self._tw()        # canvas x of column c's left edge
    def _ty(self, r): return MARGIN + r * self._th()        # canvas y of row    r's top  edge

    def _get_cell(self, x, y):
        """
        Convert a canvas pixel position (x, y) to a (row, col) grid cell,
        clamped to the valid range 0 … N-1 in each dimension.
        """
        tw, th = self._tw(), self._th()
        return (max(0, min(self.N-1, int((y - MARGIN) / th))),
                max(0, min(self.N-1, int((x - MARGIN) / tw))))

    # ── Game logic ────────────────────────────────────────────────────────────

    def _ec(self, r1, c1, r2, c2):
        """
        Return True if the tile at (r1, c1) and the tile at (r2, c2) are
        "edge-connected" — i.e., currently neighbours AND originally adjacent
        in the same direction.

        Example: if the tile at (r1,c1) originally came from row 3, col 4,
        and the tile at (r2,c2) came from row 4, col 4, and r2==r1+1 (directly
        below), they are edge-connected: they were vertically adjacent in the
        solved image and still are now.

        This is what creates a "bond": two tiles bond whenever they slide next
        to each other in their correct relative orientation.
        """
        N = self.N
        if not (0 <= r1 < N and 0 <= c1 < N and 0 <= r2 < N and 0 <= c2 < N):
            return False
        a, b  = self.tiles[r1][c1], self.tiles[r2][c2]
        dr, dc = r2-r1, c2-c1
        # Check each of the four possible neighbour directions
        if dr ==  1: return a['or']+1 == b['or'] and a['oc'] == b['oc']   # (r2,c2) is below
        if dr == -1: return a['or']-1 == b['or'] and a['oc'] == b['oc']   # (r2,c2) is above
        if dc ==  1: return a['oc']+1 == b['oc'] and a['or'] == b['or']   # (r2,c2) is right
        if dc == -1: return a['oc']-1 == b['oc'] and a['or'] == b['or']   # (r2,c2) is left
        return False

    def _flood(self, r, c):
        """
        Return the set of all grid positions reachable from (r, c) by following
        edge-connections (bonds) between adjacent tiles.

        Uses a breadth-first flood-fill.  The result is the group of tiles that
        will move together when the player drags the tile at (r, c).  A single
        unconnected tile returns a one-element set.
        """
        vis, q = {(r, c)}, [(r, c)]
        while q:
            cr, cc = q.pop(0)
            for nr, nc in [(cr-1,cc),(cr+1,cc),(cr,cc-1),(cr,cc+1)]:
                if (nr, nc) not in vis and self._ec(cr, cc, nr, nc):
                    vis.add((nr, nc))
                    q.append((nr, nc))
        return vis

    def _check_drop(self, gc, aR, aC, dR, dC):
        """
        Validate whether the dragged group can be legally dropped at the target.

        gc          : list of tile dicts in the dragged group (each has 'r','c','or','oc')
        aR, aC      : row and column of the tile the player originally clicked
        dR, dC      : row and column of the target drop position (snap grid)

        Returns a result dictionary if the move is valid, or None if not.

        A move is valid when:
          - the group stays within the grid after shifting by (dR-aR, dC-aC)
          - the number of tiles being displaced equals the number of cells
            vacated by the group (so that every displaced tile has somewhere
            to go: into the vacated cells)

        When valid, the returned dict contains:
          'dest' : where each group tile will land
          'disp' : tiles currently at the destination that must move
          'vac'  : cells that the group is leaving behind (will receive the displaced tiles)
        """
        dr, dc = dR-aR, dC-aC
        if not dr and not dc:
            return None          # no movement at all — not a valid drop
        N    = self.N
        # Calculate where each tile in the group will end up
        dest = [{'r': p['r']+dr, 'c': p['c']+dc, 'or': p['or'], 'oc': p['oc']} for p in gc]
        if not all(0 <= p['r'] < N and 0 <= p['c'] < N for p in dest):
            return None          # destination is (partly) outside the grid

        gK   = {(p['r'], p['c']) for p in gc}    # cells currently occupied by the group
        dK   = {(p['r'], p['c']) for p in dest}  # cells the group will move into

        # Cells being vacated: group cells that are NOT also destination cells
        vac  = [p for p in gc if (p['r'], p['c']) not in dK]
        # Tiles being displaced: tiles in destination cells not already in the group
        disp = [{'r': p['r'], 'c': p['c'], 't': dict(self.tiles[p['r']][p['c']])}
                for p in dest if (p['r'], p['c']) not in gK]

        if len(disp) != len(vac):
            return None          # can't swap: counts don't match

        return {'dest': dest, 'disp': disp, 'vac': vac}

    def _apply_drop(self, gc, aR, aC, dR, dC):
        """
        Perform the tile swap described by _check_drop and update self.tiles.

        First saves the current state to history (for Undo), then:
          1. Moves every tile in the group to its destination cell.
          2. Moves every displaced tile into the vacated cells.

        Returns True if the move was applied, False if it was invalid.
        """
        res = self._check_drop(gc, aR, aC, dR, dC)
        if res is None:
            return False
        self._push_history()
        # Save displaced tiles before overwriting their cells
        saved = [dict(d) for d in res['disp']]
        # Place dragged tiles at their destinations
        for p in res['dest']:
            self.tiles[p['r']][p['c']] = {'or': p['or'], 'oc': p['oc']}
        # Place displaced tiles in the vacated cells
        for i, d in enumerate(saved):
            v = res['vac'][i]
            self.tiles[v['r']][v['c']] = d['t']
        return True

    def _push_history(self):
        """
        Save a deep copy of the current tile grid to the undo history stack.
        Caps the stack at 80 entries to avoid unbounded memory use.
        """
        self.history.append([[dict(t) for t in row] for row in self.tiles])
        if len(self.history) > 80:
            self.history.pop(0)
        self.undo_btn.config(state='normal')

    def undo(self):
        """Restore the tile grid to the state before the last move."""
        if not self.history:
            return
        self.tiles = self.history.pop()
        self.solved = False
        self.undo_btn.config(state='disabled' if not self.history else 'normal')
        self.status_var.set('Drag a tile or bonded group to move it.')
        self._redraw()

    def _won(self):
        """Return True if every tile is in its original position (puzzle solved)."""
        return all(self.tiles[r][c]['or'] == r and self.tiles[r][c]['oc'] == c
                   for r in range(self.N) for c in range(self.N))

    # ── Build / shuffle ───────────────────────────────────────────────────────

    def build_grid(self):
        """
        Start a new puzzle: generate a fresh scene image, slice it into tiles,
        and shuffle the tiles using the Fisher-Yates algorithm.
        """
        self.N = int(self.grid_var.get())
        self.drag    = None
        self.solved  = False
        self.history = []
        self.undo_btn.config(state='disabled')
        self.status_var.set('Generating…')
        self.update()   # flush the UI so "Generating…" is visible during the slow step

        # Generate a new scene and pre-render each tile as a PhotoImage
        _hue[0] = random.random() * 360    # reset to a fresh random hue sequence
        scene = generate_scene(rand_bg())
        self._make_photos(scene)

        # Build the solved tile grid: tiles[r][c] starts at its correct position
        self.tiles = [[{'or': r, 'oc': c} for c in range(self.N)]
                      for r in range(self.N)]

        # Fisher-Yates shuffle: walk backwards through a flat list of positions,
        # swapping each element with a random earlier (or equal) element.
        # This produces a uniformly random permutation.
        flat = [(r, c) for r in range(self.N) for c in range(self.N)]
        for i in range(len(flat)-1, 0, -1):
            j = random.randint(0, i)
            r1, c1 = flat[i]; r2, c2 = flat[j]
            self.tiles[r1][c1], self.tiles[r2][c2] = self.tiles[r2][c2], self.tiles[r1][c1]

        self.status_var.set('Drag a tile or bonded group to move it.')
        self._redraw()

    def _make_photos(self, scene):
        """
        Slice the scene image into N×N tile images and store them in self._photos.

        self._photos maps (orig_row, orig_col) → PhotoImage.  The key is the
        tile's *original* position, not its current shuffled position.  This
        means the same PhotoImage is always used for the same piece of the
        picture regardless of where it is placed on the board.

        Source regions are computed by rounding to the nearest pixel to avoid
        cumulative rounding errors (seams) across rows and columns.

        All tile photos are resized to the same uniform pixel dimensions
        (round(_tw()) × round(_th())).  This is essential because tiles are
        shuffled: a photo sized for its original grid cell (which may be 1 pixel
        shorter or narrower than another cell due to rounding) would leave a
        1-pixel gap when placed in a slightly larger cell.  That gap exposes the
        white border halo below, showing up as horizontal white lines.  A
        uniform size eliminates the mismatch; any 1-pixel overhang at a cell
        boundary is hidden by the border halo drawn on top.
        """
        self._photos = {}
        # Use ceil, not round, so that every tile is at least as tall/wide as
        # the largest cell for that dimension.  round() can produce a size 1 px
        # *smaller* than some cells (e.g. for N=5, round(153.4)=153 but rows 1
        # and 3 are 154 px), leaving a 1-pixel gap filled by the white border
        # halo → visible white line.  With ceil the tile can be at most 1 px
        # *larger* than a cell; the overflow pixel is covered by the next tile
        # and then hidden by the border drawn on top — no gap, no line.
        tile_w = math.ceil(self._tw())   # uniform display width  for every tile
        tile_h = math.ceil(self._th())   # uniform display height for every tile
        for r in range(self.N):
            for c in range(self.N):
                # Source crop: the rectangle of the scene belonging to tile (r, c)
                x0 = round(c     * SZ   / self.N)
                y0 = round(r     * SZ_H / self.N)
                x1 = round((c+1) * SZ   / self.N)
                y1 = round((r+1) * SZ_H / self.N)
                tile = scene.crop((x0, y0, x1, y1)).resize(
                    (max(1, tile_w), max(1, tile_h)), Image.LANCZOS)
                self._photos[(r, c)] = ImageTk.PhotoImage(tile)

    # ── Drawing ───────────────────────────────────────────────────────────────

    def _redraw(self):
        """
        Repaint the entire canvas from scratch.

        Drawing order (back to front):
          1. All stationary board tiles (tile images)
          2. A coloured highlight over the drop-target cells (green=valid, red=invalid)
          3. Grid borders (white backing rectangles + black lines)
          4. The dragged tile group floating above everything else (the "ghost")
        """
        self.canvas.delete('all')
        N, tw, th = self.N, self._tw(), self._th()
        # Build a set of (row, col) positions currently being dragged so we can skip them
        drag_keys = {(p['r'], p['c']) for p in self.drag['gc']} if self.drag else set()

        # ── 1. Board tiles ────────────────────────────────────────────────────
        for r in range(N):
            for c in range(N):
                if (r, c) in drag_keys:
                    continue   # dragged tiles are drawn later, on top
                t = self.tiles[r][c]
                # Draw the tile image whose original position matches what is
                # currently at grid cell (r, c)
                self.canvas.create_image(
                    round(self._tx(c)), round(self._ty(r)),
                    image=self._photos[(t['or'], t['oc'])], anchor='nw')

        # ── 2. Drop-target highlight ──────────────────────────────────────────
        # While dragging, highlight the cells where the group would land.
        # Green = the move is valid; Red = the move would be illegal.
        if self.drag:
            dr = self.drag['snapR'] - self.drag['aR']   # row offset from anchor to snap
            dc = self.drag['snapC'] - self.drag['aC']   # col offset from anchor to snap
            if dr or dc:   # only highlight if the group has moved from its origin
                valid = self._check_drop(
                    self.drag['gc'], self.drag['aR'], self.drag['aC'],
                    self.drag['snapR'], self.drag['snapC']) is not None
                fill = '#3cc83c' if valid else '#c83c3c'
                for p in self.drag['gc']:
                    nr, nc = p['r']+dr, p['c']+dc
                    if 0 <= nr < N and 0 <= nc < N:
                        # stipple='gray50' makes the highlight semi-transparent
                        self.canvas.create_rectangle(
                            round(self._tx(nc)),   round(self._ty(nr)),
                            round(self._tx(nc+1)), round(self._ty(nr+1)),
                            fill=fill, stipple='gray50', outline='')

        # ── 3. Grid borders ────────────────────────────────────────────────────
        self._draw_borders()

        # ── 4. Drag ghost ─────────────────────────────────────────────────────
        # The ghost tiles follow the mouse cursor.  We compute the top-left corner
        # of the entire group so that any tile in the group can be placed relative
        # to it.
        if self.drag:
            gc   = self.drag['gc']
            mr   = min(p['r'] for p in gc)   # topmost row in the group
            mc   = min(p['c'] for p in gc)   # leftmost col in the group
            # 'left' and 'top' are the canvas coordinates of the group's top-left corner
            left = self.drag['curX'] - ((self.drag['aC']-mc)*tw + self.drag['offX'])
            top  = self.drag['curY'] - ((self.drag['aR']-mr)*th + self.drag['offY'])
            for p in gc:
                t = self.tiles[p['r']][p['c']]
                self.canvas.create_image(
                    round(left + (p['c']-mc)*tw),
                    round(top  + (p['r']-mr)*th),
                    image=self._photos[(t['or'], t['oc'])], anchor='nw')

    def _draw_borders(self):
        """
        Draw the grid lines between tiles.

        A border is drawn between two adjacent tiles only if they are NOT bonded
        (i.e. they do not belong to the same correctly-assembled group).  Bonded
        tiles share no visible border, giving the player a visual cue that those
        tiles are correctly assembled relative to each other.

        The outer border of the grid is always drawn regardless of bonding.

        Each border segment is drawn in two passes:
          Pass 1: a white rectangle slightly wider than the line, acting as a
                  bright halo that separates the border from the tile colours.
          Pass 2: a thin black line on top of the white halo.
        """
        N = self.N

        def hN(sr, sc):
            """True if a horizontal border is needed at the top of row sr, column sc."""
            if not (0 <= sc < N): return False
            if sr == 0 or sr == N: return True           # always draw outer edges
            return not self._ec(sr-1, sc, sr, sc)        # draw if tiles above/below are not bonded

        def vN(sc, sr):
            """True if a vertical border is needed at the left of column sc, row sr."""
            if not (0 <= sr < N): return False
            if sc == 0 or sc == N: return True           # always draw outer edges
            return not self._ec(sr, sc-1, sr, sc)        # draw if tiles left/right are not bonded

        # Pass 1: white backing rectangles (drawn as thick rectangles, BW pixels wide)
        for sr in range(N+1):
            for sc in range(N):
                if not hN(sr, sc): continue
                cy = round(self._ty(sr))
                x1, x2 = round(self._tx(sc)), round(self._tx(sc+1))
                self.canvas.create_rectangle(x1-BW, cy-BW, x2+BW, cy+BW,
                                              fill='white', outline='')
        for sc in range(N+1):
            for sr in range(N):
                if not vN(sc, sr): continue
                cx = round(self._tx(sc))
                y1, y2 = round(self._ty(sr)), round(self._ty(sr+1))
                self.canvas.create_rectangle(cx-BW, y1-BW, cx+BW, y2+BW,
                                              fill='white', outline='')

        # Pass 2: black lines on top of the white halos
        for sr in range(N+1):
            for sc in range(N):
                if not hN(sr, sc): continue
                cy = round(self._ty(sr))
                x1, x2 = round(self._tx(sc)), round(self._tx(sc+1))
                self.canvas.create_line(x1, cy, x2, cy, fill='black', width=1)
        for sc in range(N+1):
            for sr in range(N):
                if not vN(sc, sr): continue
                cx = round(self._tx(sc))
                y1, y2 = round(self._ty(sr)), round(self._ty(sr+1))
                self.canvas.create_line(cx, y1, cx, y2, fill='black', width=1)

    # ── Mouse handlers ────────────────────────────────────────────────────────

    def _on_down(self, e):
        """
        Called when the player presses the mouse button on the canvas.

        Identifies which tile was clicked, finds all tiles bonded to it via
        flood-fill, and sets up self.drag to track the ongoing drag operation.

        self.drag keys:
          'gc'    : list of tiles in the dragged group (each: {'r','c','or','oc'})
          'aR','aC': row/col of the tile that was actually clicked (the "anchor")
          'offX','offY': pixel offset of the click within the anchor tile cell,
                         so the tile doesn't jump to centre under the cursor
          'curX','curY': current mouse position (updated in _on_move)
          'snapR','snapC': the grid cell the group's anchor is snapping toward
        """
        r, c = self._get_cell(e.x, e.y)
        g    = self._flood(r, c)      # find the bonded group
        tw, th = self._tw(), self._th()
        gc   = [{'r': gr, 'c': gc_, **self.tiles[gr][gc_]} for gr, gc_ in g]
        self.drag = {
            'gc': gc, 'aR': r, 'aC': c,
            'offX': e.x - (MARGIN + c*tw),   # click offset within the anchor tile
            'offY': e.y - (MARGIN + r*th),
            'curX': e.x, 'curY': e.y,
            'snapR': r,  'snapC': c,
        }
        self.canvas.config(cursor='fleur')   # change cursor to a four-arrow move icon
        n = len(gc)
        self.status_var.set(f'Dragging group of {n}.' if n > 1 else 'Dragging tile.')
        self._redraw()

    def _on_move(self, e):
        """
        Called continuously as the mouse moves while the button is held.

        Updates the current mouse position and recalculates which grid cell the
        anchor tile is snapping toward.  The snap position is rounded to the
        nearest cell centre (hence the +tw/2 and +th/2 before dividing).
        """
        if not self.drag:
            return
        tw, th = self._tw(), self._th()
        self.drag['curX']  = e.x
        self.drag['curY']  = e.y
        self.drag['snapC'] = max(0, min(self.N-1,
            int((e.x - MARGIN - self.drag['offX'] + tw/2) / tw)))
        self.drag['snapR'] = max(0, min(self.N-1,
            int((e.y - MARGIN - self.drag['offY'] + th/2) / th)))
        self._redraw()

    def _on_up(self, e):
        """
        Called when the player releases the mouse button.

        Attempts to apply the drop at the current snap position.  If the move is
        valid the tiles are swapped; if not, the dragged tiles snap back to their
        original positions (because self.drag is cleared and _redraw repaints the
        board from self.tiles which is unchanged).

        After any drop, checks whether the puzzle has been solved.
        """
        if not self.drag:
            return
        self.canvas.config(cursor='hand2')
        self._apply_drop(self.drag['gc'], self.drag['aR'], self.drag['aC'],
                         self.drag['snapR'], self.drag['snapC'])
        self.drag = None
        if self._won():
            self.solved = True
            self.status_var.set('🎉 Puzzle solved!')
        else:
            self.status_var.set('Drag a tile or bonded group to move it.')
        self._redraw()


if __name__ == '__main__':
    TilePuzzleApp().mainloop()
